apiVersion: v2
name: fuel-prices
description: Diagrammdienst für Rohöl-, Benzin- und Dieselpreise in Deutschland und Polen
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - fuel
  - prices
  - petrol
  - diesel
  - brent
home: https://github.com/eumel8/fuel-prices
sources:
  - https://github.com/eumel8/fuel-prices
maintainers:
  - name: eumel8
    url: https://github.com/eumel8